### ISSUE TITLE
OSS2 causes inconsistent aliyun-python-sdk-core solutions.

### ISSUE THREAD

**Issue by asford** [conda-forge/oss2-feedstock#15]
Not *entirely* sure if this belongs here or the downstread feedstocks, but this feedstock causes an inconsistent solution of the `aliyun-python-sdk-core` package on python 3. This is due to the version-specific core sdk pin at:

https://github.com/conda-forge/oss2-feedstock/blob/ece2e6b8cafde10d56874e54b2211dab0c5ca0fd/recipe/meta.yaml#L25-L27

This is because `aliyun-python-sdk-kms` *does not* use a python-version specific sdk version

https://github.com/conda-forge/aliyun-python-sdk-kms-feedstock/blob/c1af2597b9bb6cc4f48d50b8f06c43da28750340/recipe/meta.yaml#L22-L23

It looks like `aliyun-python-sdk-core` has been python-3 compatible from `2.13.5` onwards, and has been python-3 *only* from `2.13.15` onwards. At this point, I think it would be safe to just target `aliyun-python-sdk-core` and let the solver work around the appropriate version.

You can see this in a test solve (trimmed for clarity):

```bash

$ conda create --dry-run -n oss2-test -c conda-forge oss2 python=3

[...]

The following NEW packages will be INSTALLED:
  
  aliyun-python-sdk~ conda-forge/linux-64::aliyun-python-sdk-core-2.13.26-py38h32f6830_1
  aliyun-python-sdk~ conda-forge/linux-64::aliyun-python-sdk-core-v3-2.13.11-py38h32f6830_1
  aliyun-python-sdk~ conda-forge/noarch::aliyun-python-sdk-kms-2.12.0-pyh9f0ad1d_0
  oss2               conda-forge/linux-64::oss2-2.13.0-py38h32f6830_0
  python             conda-forge/linux-64::python-3.8.6-h852b56e_0_cpython

[...]
```

Vrs the python 2 solve:

```bash
$ conda create --dry-run -n oss2-test -c conda-forge oss2 python=2

[...]

The following NEW packages will be INSTALLED:

  aliyun-python-sdk~ conda-forge/linux-64::aliyun-python-sdk-core-2.13.15-py27h8c360ce_1
  aliyun-python-sdk~ conda-forge/noarch::aliyun-python-sdk-kms-2.12.0-pyh9f0ad1d_0
  oss2               conda-forge/linux-64::oss2-2.9.1-py27_0
  python             conda-forge/linux-64::python-2.7.15-h5a48372_1011_cpython

[...]
```

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by efiop** [comment]
Fixed by #16
